MODEL:
  NAME: 'ResNet50'
  
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  PADDING: 10

DATASETS:
  NAMES: ('Market1501')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 16
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 1720
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 16

  STEP: 40
  GAMMA: 0.1

  CHECKPOINT_PERIOD: 80
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128
  LOAD_EPOCH: 120
  

OUTPUT_DIR: "./checkpoint/Market1501/Softmax_Triplet"
DEVICE: "cuda:0"
